define([], function() {
  "use strict";
  var ActivityLogLocale = function() {
    return {
      root: {
        labels: {
          header: "Activity Log ({count})",
          ACCOUNT_FINANCIAL: "Accounts Financial",
          ACCOUNT_NON_FINANCIAL: "Accounts Non Financial",
          PAYMENTS: "Payments",
          BULK: "Bulk",
          BULK_FILE: "Bulk File",
          BENEFICIARY: "Beneficiary",
          OTHER_TRANSACTION: "Other transactions",
          OTHER_TRANSACTION_COUNT: "Other transactions ({count})",
          ACCOUNT_FINANCIAL_COUNT: "Accounts Financial ({count})",
          ACCOUNT_NON_FINANCIAL_COUNT: "Accounts Non Financial ({count})",
          PAYMENTS_COUNT: "Payments ({count})",
          BULK_COUNT: "Bulk ({count})",
          BULK_FILE_COUNT: "Bulk File ({count})",
          PAYEE_BILLER_COUNT: "Payee and Biller ({count})",
          PAYEE_BILLER: "Payee and Biller",
          BULK_RECORD: "Bulk Record",
          BULK_RECORD_COUNT: "Bulk Record ({count})",
          TRADE_FINANCE_COUNT: "Trade Finance ({count})",
          BULK_RECORD_NON_FINANCIAL_COUNT: "Bulk Record Non Financial ({count})",
          BULK_FILE__NON_FINANCIAL_COUNT: "Bulk File Non Financial ({count})",
          FU_R_DP: "Domestic Payee",
          FU_F_DP: "Domestic Payee",
          FU_R_ILP: "International Payee",
          FU_F_ILP: "International Payee",
          FU_R_DDP: "Demand Draft Payee",
          FU_F_DDP: "Demand Draft Payee",
          FU_F_IP: "Internal Payee",
          FU_R_IP: "Internal Payee",
          FU_F_MPY: "Mixed Payee",
          RT_N_CAC: "Create Corporate Admin Report",
          RT_N_CAD: "Delete Corporate Admin Report",
          RT_N_CAR: "Request Admin Report",
          RT_N_CAU: "Update Corporate Admin Report",
          RT_N_CUR: "Request User Report",
          RT_N_DAR: "Cancel Admin Report",
          RT_N_DUR: "Cancel User Report",
          RT_N_UAR: "Update Admin Report",
          RT_N_UUM: "Update User Report Mapping",
          RT_N_UUR: "Update User Report",
          date: "Date",
          type: "Type",
          referenceNo: "Reference No",
          initiatedBy: "Initiated By",
          status: "Status",
          accountsFinancial: "Accounts Financial",
          accountsNonFinancial: "Others",
          transactionType: "Transaction Type",
          accountNumber: "Account Number",
          accountName: "Account Name",
          amount: "Amount",
          debitAccountNumber: "From Account",
          beneficiaryAccountNumber: "Payee Account Details",
          beneficiaryName: "Payee Account Name",
          beneDetails: "Beneficiary Name",
          description: "Description",
          payee: "Payee/Biller Name",
          payeeType: "Payee Type",
          category: "Category",
          payeeAccountDetails: "Payee Account Details",
          list: "Activity Log Details",
          accountsFinancialList: "Financial Accounts List",
          accountsNonFinancialList: "Non-Financial Accounts List",
          tradeFinanceList: "Trade Finance List",
          beneficiaryList: "Beneficiary Details List",
          bulkFileList: "Bulk Files List",
          bulkRecordList: "Bulk Records List",
          paymentList: "Payment Transaction List",
          totalFileAmount: "File Amount",
          approvalType: "Approval Type",
          fileIdentifierDetail: "File Identifier",
          fileName: "File Name",
          valueDate: "Value Date",
          debitAccountNo: "Debit Account",
          creditAccountNo: "Credit Account No",
          paymentType: "Payment Type",
          recordStatus: "Record Status",
          fileRefId: "File Reference Number",
          recRefId: "Record Reference Number",
          fileReferenceNo: "File Reference Number",
          createdBy: "{FName} {LName}",
          details: "Click to see details of {transactionId}",
          detailText: "Transaction ID {transactionId}",
          payeeName: "Payee Name-{payeeName}",
          uploaded: "Uploaded",
          deleted: "Deleted",
          approvals: "Approvals",
          activityLogheader: "Activity Log ({count})",
          pendingApprovalheader: "Pending For Approvals ({count})",
          approvedLogHeader: "My Approved List ({count})",
          NON_FINANCIAL_BULK_FILE: "Non Financial Bulk File",
          NON_FINANCIAL_BULK_RECORD: "Non Financial Bulk Record",
          TRADE_FINANCE: "Trade Finance",
          PARTY_MAINTENANCE: "Corporate",
          ADMIN_MAINTENANCE: "Admin",
          BULK_FILE_ADMIN: "Bulk File Admin",
          BULK_RECORD_ADMIN:"Bulk Record Admin",
          dateFrom: "Date From",
          dateTo: "Date To",
          search: "Search",
          back: "Back",
          downloadEreceipt: "e-Receipt",
          filterAlt: "Click here to filter results by date",
          filter: "Filter results by date",
          mobileClick: "Click here to enter {module}",
          mobileClickTitle: "Click to enter {module}",
          eReceiptDownload: "Click here to download E Receipt",
          eReceiptDownloadAlt: "Download E Receipt",
          chooseTxnType: "Choose Transaction Type",
          financialTxn: "{count} Financial",
          nonFinancialTxn: "{count} Non Financial",
          gracePeriod: "Grace Period",

          forexDealListTable: "Forex Deal List",
          forexDealList: "Forex Deal",
          FOREX_DEAL: "Forex Deal",
          currencyCombination: "Currency Combination",
          dealType: "Deal Type",
          dealPatternType: {
              S: "Spot",
              F: "Forward"
          },
          dealAmountCp: "{rateType} {currency}",
          buy: "Buy",
          sell: "Sell"
        },
        status: {
          PENDING_APPROVAL: "In Progress",
          REJECTED: "Rejected",
          APPROVED: "Processed",
          INITIATED: "Initiated",
          COMPLETED: "Processed",
          EXPIRED: "Expired",
          MODIFICATION_REQUESTED: "Modification Requested"
        },
        navBarDescription: "Approved Transactions",
        toolTipMesssage: "You can approve this transaction on or before {maxDate}"
      },
      ar: true,
      fr: true,
      cs: true,
      sv: true,
      en: false,
      "en-us": false,
      el: true
    };
  };
  return new ActivityLogLocale();
});
