require.config({
    paths: {
        "ojs": "framework/js/libs/oraclejet/js/libs/oj/v5.0.0/min",
        "ojL10n": "framework/js/libs/oraclejet/js/libs/oj/v5.0.0/ojL10n",
        "ojtranslations": "framework/js/libs/oraclejet/js/libs/oj/v5.0.0/resources",
        "jquery": "framework/js/libs/oraclejet/js/libs/jquery/jquery-3.3.1.min",
        "knockout": "framework/js/libs/oraclejet/js/libs/knockout/knockout-3.4.2",
        "knockout-helper": "framework/js/plugins/amd-helper",
        "knockout-mapping": "framework/js/libs/oraclejet/js/libs/knockout/knockout.mapping-latest",
        "text": "framework/js/libs/oraclejet/js/libs/require/text",
        "jqueryui-amd": "framework/js/libs/oraclejet/js/libs/jquery/jqueryui-amd-1.12.1.min",
        "paperAccordion": "framework/js/pages/accordion",
        "baseService": "framework/js/base-models/service-base",
        "abstractBaseModel": "framework/js/base-models/abstract-base-model",
        "baseLogger": "framework/js/base-models/logging-base",
        "baseModel": "framework/js/base-models/ko/base-model",
        "base-model": "framework/js/base-models/base-model",
        "base-models": "framework/js/base-models",
        "promise": "framework/js/libs/oraclejet/js/libs/es6-promise/es6-promise.min",
        "hammerjs": "framework/js/libs/oraclejet/js/libs/hammer/hammer-2.0.8.min",
        "ojdnd": "framework/js/libs/oraclejet/js/libs/dnd-polyfill/dnd-polyfill-1.0.0.min",
        "css": "framework/js/libs/oraclejet/js/libs/require-css/css.min",
        "require-config": "framework/js/pages/require-config",
        "css-builder": "framework/js/libs/oraclejet/js/libs/require-css/css-builder",
        "customElements": "framework/js/libs/oraclejet/js/libs/webcomponents/custom-elements.min",
        "normalize": "framework/js/libs/oraclejet/js/libs/require-css/normalize",
        "json": "framework/js/plugins/json",
        "thirdPartyLibs": "framework/js/libs",
        "platform": "framework/js/base-models/platform",
        "webAnalytics": "framework/js/base-models/web-analytics",
		"fetch": "framework/js/libs/oraclejet/js/libs/opt/min/impl/fetch",
        "framework/js/constants/constants": "empty:",
        "extensions": "empty:",
        "lzn": "empty:"
    }
});
